### ISSUE TITLE
ClassicEtherWallet updates and MEW patches

### ISSUE THREAD

**Issue by Dexaran** [EthereumCommonwealth/Roadmap#26]
- [x] 1. Merge 3.10.2 MEW updates into ClassicEtherWallet
- [x] 2. Make ETC node a default one on CEW
- [x] 3. Color patch for MEW and CEW
- [x] 4. Replace "MyEtherWallet" mentions by "ClassicEtherWallet" info on ClassicEtherWallet 
- [x] 5. Add default contracts and tokens
- [x] 6. Crosschain ENS lookup ([link](https://github.com/EthereumCommonwealth/Roadmap/issues/26#issuecomment-324541572))
- [x] 7. Add DexNS support to CEW / make a patch to MEW ([link 1](https://github.com/EthereumCommonwealth/Roadmap/issues/26#issuecomment-329995944))
- [x] 8. Add ClassicMask support on CEW / make a patch to MEW
- [x] 9. Improve modular ENS support on MEW and CEW
- [x] 10. Adapt new token interface.
- [x] 11. Add a multi-currency balance display. ([link](https://github.com/EthereumCommonwealth/Roadmap/issues/26#issuecomment-329996411))
- [x] 12. Support adding custom tokens by DexNS token names.

**Comment by Dexaran** [comment]
Detailed description of required changes:

## 1. Merge 3.10.2 MEW updates into ClassicEtherWallet

I think that it is needed to update CEW to support all recent MyEtherWallet upgrades. The most important things are:

 - MetaMask support. This will also be useful to have since we will create ClassicMask and it will require the same functionality.

 - UBQ / Expanse / RSK / Musicoin nodes support added with corresponding color patches.

**Comment by randytorres** [comment]
@Dexaran I forked a fresh version of MEW and made some changes to the home page replacing some of the MEW references with CEW. I also made ETC node on default which would complete task #2.
https://github.com/randytorres/etherwallet/commit/aa1a5a6ae040fc02240c9f7781aefd5261e71e29

I should be able to complete tasks 1-4 over the weekend.

**Comment by Dexaran** [comment]
I will also ask to place the ETC node at the top of the node list in CEW. (ETH nodes are at the top at the moment)

We will also need to change the name lookup with modular ENS support patch. We need to create a customisable lookup to add DexNS support in future. I will provide more updates about this soon.

**Comment by randytorres** [comment]
@Dexaran I removed a lot of references to MEW and added the dynamic colors. As far as removing mentions of MEW, should I remove ALL mentions including and links to their github, help channels/rooms, donation addresses, etc?

https://github.com/randytorres/etherwallet/commit/dde63548c4f9063ce733237a9442179762876cdb

**Comment by Dexaran** [comment]
@randytorres Let's leave links to github, help channels/rooms, as is for now. Let's replace the donation address with Ethereum Commonwealth address: `0x52823e725a34d42e14a1b66fb67299c30c4d8edf`

I'd like to mention some issues with [your current implementation](https://github.com/randytorres/etherwallet/tree/add-color-and-replace-mew).

1. Yellow color theme is a native color theme of Musicoin. Let's change the color theme of all testnets to gray #C4C4C4 and replace Musicoin with colors with yellow.

2. Dark buttons like "Generate transaction" should also be affected by the color theme. They should be darker but change their colors. A user often pays attention to the buttons that they click.

![image](https://user-images.githubusercontent.com/26142412/29505511-cec2865a-8614-11e7-9868-d6fd7be39e44.png)

3. MEW logo should be replaced.

![mew_logo](https://user-images.githubusercontent.com/26142412/29505694-b51c10f8-8615-11e7-99e0-32b48c73fa32.png)

**Comment by randytorres** [comment]
Aright I made the changes you requested. I tried creating a CEW favicon based off the logo but It doesn't look very good, do you have a favicon.ico of the logo by any chance?

**Comment by randytorres** [comment]
Hey @Dexaran I just finished adding ENS support and included it in the PR. 
https://github.com/Dexaran/etherwallet/pull/3/commits/862eec31085d1be3158d24bb2380d4e71439488c

**Comment by Dexaran** [comment]
Let's start crosschain ENS lookup:

1. Add the lookup dropdown button. It should contain `ENS (.eth)` and `ECNS (.etc)` now. We will add UBQ and EXP as soon as ENS will be deployed on this chains.

2. I think that we need to initialize a second instance of web3 to perform a lookup on the corresponding chain. If the user has unlocked account under ETC chain but he wishes to send 1 ETC to the `dexaran.eth` then we should find the address that is associated with `dexaran.eth` in ENS on ETH chain  (using Infura API endpoint). Take the address and send a transaction to this address on ETC chain (using Epool API).

3. If the user has typed `dexaran.eth` but the Lookup source is set to ECNS then we should automatically switch the Lookup source to the ENS and update the Lookup dropdown button. `.eth` resolutions **must** always result in ENS lookup and `.etc` resolutions **must** result in ECNS lookup.

**Comment by Dexaran** [comment]
Replace unlocking wallet "MetaMask / Mist" menu item by "MetaMask or ClassicMask / Mist" since ClassicMask is supported as well.

**Comment by Dexaran** [comment]
# Support adding custom tokens by DexNS token names

# 1.

 We should add the third menu item to add custom tokens on CLassicEtherWallet as follows:

![token_by_name](https://user-images.githubusercontent.com/26142412/30515750-95535f4a-9b3e-11e7-8ae1-9dab66dd3183.png)

# 2.

If the user has clicked the new `"Add custom token by token name (DexNS)"` menu item then we should connect to ETC network (initialize an instance of web3 with ETC API endpoint provider) and dropdown the DexNS token adding menu:

![dexns__token_search_dropdown_unfinished](https://user-images.githubusercontent.com/26142412/30515770-262320a0-9b3f-11e7-9d02-5682faf7089a.png)

DexNS token adding menu should contain only one input item "Token symbol" (string text) and one button "SEARCH".

# 3.

 CEW should perform a `getName("inputted name")` function call to DexNS Storage contract when the user has typed the token name and clicked the "SEARCH" button. We should parse the result of the call to extract associated address and stringified metadata of the desired contract.

Example of the call with the "GNT" input will be represented in the following format:

![dexns_call_result](https://user-images.githubusercontent.com/26142412/30515845-cce31d4a-9b40-11e7-9ff8-e588d9efcfb3.png)

# 4.

If the extraction of the metadata was successful then we should parse it again. Metadata is returned in the following format:

`-<network id flag> -A <abi> -flag1 flag1_params -flag2 flag2_params -i <information> ...`

Example of the metadata:

`-ETC -A [{"constant":false,"inputs":[],"name":"foo","outputs":[],"payable":false,"type":"function"}]` where `-ETC` means that the desired contract is deployed in the ETC network, and `-A` is the flag that predicts that the next symbols pattern will be a separator (whitespace) and the ABI of the desired contract.

We should take the chain id parameter (-ETC / -ETH / -UBQ or -EXP) and throw away anything else.

# 5.

If everything is fine then we should dropdown the menu to suggest user to save the desired token.

We should display the "SUCCESS" result to the user at the bottom of the token symbol input box.

Save token menu should contain two input fields.

- Token network: this should be the parsed network id flag from the DexNS name metadata by default. If no network id flag was presented then we should display the current selected node here.

- Information: "You are going to add token to your $chain_id tokens"

![dexns__token_search_dropdown_light](https://user-images.githubusercontent.com/26142412/30516127-f03815b0-9b46-11e7-8d6c-2bec2300ce63.png)

# 6.

 We should call the desired token address with by the default ERC20 ABI to extract token decimals after the "SAVE" button was pressed. Then we should add the desired token to user's tokens at the specified chain.

IMPORTANT: We should add token to the specified chain that was extracted from DexNS name metadata. It doesn't matter if the user is currently on the matching chain or on any of the alternative chains.

**Comment by Dexaran** [comment]
# Multi-currency balance display.

Let CLassicEtherWallet display user balances on different chains: ETH / ETC / EXP / UBQ.

We should perform four calls to access user's balances on different chains when unlocking account/ displaying balances.

We should display the corresponding balance as "active". For example if the user is currently on ETC network then we should display ETC balance with big digits and black color. ETH / UBQ / EXP balances should be displayed with small digits and gray color on ETC network.

# Examples

![cew_multiple_currencies](https://user-images.githubusercontent.com/26142412/30516205-d2e8b4e0-9b48-11e7-8840-82a72e0b572a.png)

![cew_multiple_currencies2](https://user-images.githubusercontent.com/26142412/30516206-d8566558-9b48-11e7-9f84-9c0a13dff389.png)

**Comment by yograterol** [comment]
![token-cew](https://user-images.githubusercontent.com/3322886/30517515-c7d2f78a-9b27-11e7-8e13-e68646551496.gif)


https://github.com/EthereumCommonwealth/etherwallet/pull/6

**Comment by Dexaran** [comment]
Fix the problem of an accidentally transaction sending to the contract in the wrong chain.

GNT contract: https://etherscan.io/token/Golem?a=0xa74476443119a942de498590fe1f2454d7d4ac0d
It is deployed on ETH chain

GNT contract address on ETC chain (no contract): http://gastracker.io/addr/0xa74476443119a942de498590fe1f2454d7d4ac0d

This is the same address on ETC chain and it contains 5000 ETC ($60,000 at the moment)

The problem is that Golem (or any other) contract can reject Ether (ETH on Ethereum chain) but there is no contract on ETC chain. If they send ETH to the contract address then the transaction will fail. If they will send ETC/ UBQ/ EXP to the same address (there is no contract on this address on ETC/ UBQ/ EXP chains at all. It's just an address without bytecode) then the transaction will submit and ETC would be lost.

We need:

1. If the user is trying to send a transaction with >30 000 GAS and `Data` then he is trying to call something and we need to check if the receiver is a contract on the selected chain or not

2. Check if the receiver is a contract or not

3. If the receiver is not a contract then warn the user:
"WARNING! It looks like you are trying to call the contract on `$chain_name` chain. The destination address is not a `$chain_name` contract. Are you sure want to do it?"

4. If the user has clicked YES then it's his own problems (may be he is sending hex-encoded message as transaction data) if NO then we have saved his funds

**Comment by yaronvel** [comment]
Maybe before issuing the warning check that there is a contract on same address in ETH?

**Comment by Dexaran** [comment]
The desired contract may be deployed on any of the alternative chains (not only ETH). Checking all of the existent chains doesn't seem to be a good idea.
Furthermore, if the user has mistyped the address of the ETC contract this will save him as well.

**Comment by yaronvel** [comment]
Btw, doesnt the wallet calculate gas limit automatically for users?

**Comment by Dexaran** [comment]
I would say that MEW is calculating gas limit automatically but the user has an opportunity to change it at will.

**Comment by yograterol** [comment]
DexNS support to add custom tokens

https://github.com/EthereumCommonwealth/etherwallet/pull/10

![dexns](https://user-images.githubusercontent.com/3322886/31590122-dabe8e30-b1d0-11e7-9014-80260afedafe.gif)

**Comment by Dexaran** [comment]
I suppose that we need to make some changes to avoid user confusion:

1. Add "Loading..." text or loading animation that will appear to show the user that searching is currently in progress. This should disappear when the response will be retreived.

2. Start searching (send async requests) 2 seconds after user has typed any character. Token symbols are not limited to 3-characters. For example AE (AEternity token) and SNGLS are not 3 characters length.

3. When changing the network CEW shows that token is not a valid ERC20 token if this token is deployed on alternative chain. I suppose that this behavior will cause user confusion. I suppose that CEW should remember what network the token uses and hide all the tokens that belong to previous chain when you are switching to new chain.

**Comment by yograterol** [comment]
@Dexaran I agree, I'll do it

**Comment by Dexaran** [comment]
It would be nice to allow adjusting gas price in 0.1 GWEI instead of 1 GWEI to ClassicMask and CEW. MEW recently did it: https://github.com/kvhnuke/etherwallet/releases/tag/v3.10.5

Not a critical issue, but nice to have.

**Comment by Dexaran** [comment]
![cew_rineth](https://user-images.githubusercontent.com/26142412/31931477-4164d40c-b89b-11e7-9090-abb3ee9024e4.png)

CEW displays RinkebyETH and ETH as the same amounts of currencies while they are different separate currencies.

**Comment by Dexaran** [comment]
Update:

[x] Crosschain DexNS lookup for custom tokens - finished.
[x] Crosschain DexNS lookup for Names and sending transactions - finished.
[x] "Not a valid ERC-20 token" error of custom token when not on token network - fixed.
[x] Warning about an attempt to execute a token contract on alternative chain - finished.
[ ] TODO: testnet Ether is considered ETH currency and displayed as ETH balance.
[ ] TODO: double "You have successfully connected to $network" popup message when querying network via URL.
[ ] TODO: "Loading..." text or animation when DexNS is currently seraching but the response is not yet received.
[ ] TODO: 1.3 second delay between typing and lookup execution to allow user to type a full name first.

**Comment by yograterol** [comment]
https://github.com/EthereumCommonwealth/Roadmap/issues/26#issuecomment-338910299 It's not a problem anymore

**Comment by Dexaran** [comment]
CEW bugs that needs to be fixed:

1. "Add custom token by token Symbol" starts to search token when you type 3 characters. If you type 4-characters of token symbol then CEW throws error because of the first three symbols are not found even if 4-characters symbol string represents a valid token name.

2. S-ETH symbol is successfully found but could not be added to token list. I suppose that it's because of `-` character.

3. Adding tokens with already-existing symbol results in same tokens added multiple times.

**Comment by yograterol** [comment]
https://github.com/EthereumCommonwealth/Roadmap/issues/26#issuecomment-345657999 Fixed

**Comment by Dexaran** [comment]
Merged https://github.com/EthereumCommonwealth/etherwallet/pull/14

**Comment by Dexaran** [comment]
BUG: CEW automatically evaluates gaslimit to -1 when trying to deploy contract. If I set the gaslimit to 4700000 then contract is successfully deployed.

**Comment by Dexaran** [comment]
Point 9 resolved with the latest update.
